models/movie.py
import uuid
from extensions import db


class Movie(db.Model):
    __tablename__ = "movies"
    id = db.Column(db.String(50), primary_key=True, default=lambda: str(uuid.uuid4()))
    name = db.Column(db.String(100))
    poster = db.Column(db.String(255))
    rating = db.Column(db.Float)
    summary = db.Column(db.String(500))
    trailer = db.Column(db.String(255))

    # JSON = keys
    def to_dict(self):
        return {
            "id": self.id,
            "name": self.name,
            "poster": self.poster,
            "rating": self.rating,
            "summary": self.summary,
            "trailer": self.trailer,
        }

routes/movies_list_bp.py
from flask import Blueprint, jsonify, render_template, request
from flask_login import login_required
from flask_sqlalchemy import SQLAlchemy
from extensions import db
from models.movie import Movie

movies_list_bp = Blueprint("movies_list", __name__)


# Task 2: /movies-list -> Display the data on the page from Azure (MSSQL)
# Movie list dashboard
@movies_list_bp.route("/")  # HOF
@login_required
def movie_list_page():
    movie_list = Movie.query.all()  # Select * from movies | movie_list iterator
    data = [movie.to_dict() for movie in movie_list]  # list of dictionaries
    return render_template("movies.html", movies=data)


# Task 3: /movies-list/99 -> Display the data on the page from Azure (MSSQL)
# Movie list detail
@movies_list_bp.route("/<id>")  # HOF
@login_required
def movie_detail_page(id):
    filtered_movie = Movie.query.get(id)
    if filtered_movie:
        data = filtered_movie.to_dict()
        return render_template("movie.html", movie=data)
    else:
        return "<h1>Movie not found</h1>"


@movies_list_bp.route("/add", methods=["GET"])  # HOF
@login_required
def add_movie():
    return render_template("movie_form.html")


@movies_list_bp.route("/delete", methods=["POST"])  # HOF
def delete_movie_by_id():
    print(request.form.get("movie_id"))
    id = request.form.get("movie_id")
    filtered_movie = Movie.query.get(id)
    if not filtered_movie:
        return "<h1>Movie not found</h1>", 404

    try:
        data = filtered_movie.to_dict()
        db.session.delete(filtered_movie)
        db.session.commit()  # Making the change (update/delete/create) permanent
        return f"<h1>{data['name']} Movie deleted Successfully</h1>"
    except Exception as e:
        db.session.rollback()  # Undo the change
        return f"<h1>Error happened {str(e)}</h1>", 500


@movies_list_bp.route("/success", methods=["POST"])  # HOF
def create_movie():
    # Creating a dictionary
    data = {
        "name": request.form.get("name"),
        "poster": request.form.get("poster"),
        "rating": request.form.get("rating"),
        "summary": request.form.get("summary"),
        "trailer": request.form.get("trailer"),
    }

    new_movie = Movie(**data)
    try:
        db.session.add(new_movie)
        db.session.commit()
        # movies.append(new_movie)
        return f"<h1>{data['name']} Movie added Successfully</h1>"
    except Exception as e:
        db.session.rollback()  # Undo the change
        return f"<h1>Error happened {str(e)}</h1>", 500


@movies_list_bp.route("/update/<id>", methods=["POST"])
def update_movie_by_id_form(id):
    filtered_movie = Movie.query.get(id)
    if not filtered_movie:
        return "Movie could not be found"
    movie_data = filtered_movie.to_dict()
    try:
        for key, value in movie_data.items():
            if hasattr(filtered_movie, key):
                setattr(filtered_movie, key, value)

        db.session.commit()
        return "<h1>Updated Successfully</h1>"
    except Exception as e:
        return "Movie update error"

templates/about.html
{% extends 'base.html' %}

{% block body %}
   
    <!-- mustache -->
    {% for user in users %}
    <div class="user-container">
      <img class="user-pic" src="{{user.pic}}" alt="Profile picture" />
      <p class="user-msg">
        Hello,
        <span class="user-name"
          >{{user.name}} {{ "🚀" if user.pro else "🎊🎊" }}
        </span>
      </p>
    </div>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
    <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
    crossorigin="anonymous"
  />
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand">Movie App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/movies">Movie List</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/register">Register</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  {% with messages = get_flashed_messages() %}
    {% if messages %}
      <ul class=flashes>
      {% for message in messages %}
        <li>{{ message }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  {% endwith %}
    {% block body %}
    {% endblock %}
</body>
</html>

templates/forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form class="login-form" 
    action="{{url_for('dashboard_login_page')}}"
    method="POST">
    <h6>Username</h6>
    <input name="username" type="text" />
    <h6>Password</h6>
    <input name="password" type="password" />
    <input type="submit" value="Login" />
    </form>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
    crossorigin="anonymous"
  />
    <title>Document</title>
</head>
<body>
    <div class="container">

    <h1>Login:</h1>


    <form method="POST" action="">
        <!-- action="" submit to current url -->
        <!-- Validations -->

        {{form.hidden_tag()}}

        {% if form.username.errors %}
            {% for error in form.username.errors %}
                <div style="color:red">{{error}}</div>
            {% endfor %}
            
        {% endif %}
        {% if form.password.errors %}
            {% for error in form.password.errors %}
                <div style="color:red">{{error}}</div>
            {% endfor %}
        {% endif %}



        {{form.hidden_tag()}}
        <div class="form-group">
        {{form.username.label}}:
        {{form.username(placeholder="Username", class="form-control")}}
    </div>
        <div class="form-group">
        {{form.password.label}}
        {{form.password(class="form-control")}}
    </div>
        <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
    </div>
    </form>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
      crossorigin="anonymous"
    ></script>
</body>
</html>

templates/movie.html
{% extends 'base.html' %}

{% block body %}
    <h1>Movie Detail</h1>

    <div class="movie-container">
        <iframe
        width="100%"
        height="720"
        src="{{movie.trailer}}"
        title={{movie.name}}
        frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
        allowfullscreen
      ></iframe>
    <div class="movie-spec">
            <h3>{{movie.name}}</h3>
            <h3>⭐ {{movie.rating}}</h3>
        </div>
        <p>{{movie.summary}}</p>
    </div>
    {% endblock %}

templates/movie_form.html
{% extends 'base.html' %}

{% block body %}
    <h4>Add New Movie</h4>
    <form action="{{ url_for('movies_list.create_movie') }}" method="post" class="add-movie-form">
        <input type="text" name="name" placeholder="Name">
        <input type="text" name="poster" placeholder="Poster URL">
        <input type="number" step="0.1" name="rating" placeholder="Rating">
        <textarea name="summary" placeholder="Summary"></textarea>
        <input type="text" name="trailer" placeholder="Trailer URL">
        <button type="submit">Add Movie</button>
    </form>

{% endblock %}

templates/movies.html
{% extends 'base.html' %}

{% block body %}
    <h1>Movies Dashboard</h1>

    <a href="/add_movie"><button class="btn btn-primary">Add New Movie</button></a>

    <div class="movie-list-container">
    {% for movie in movies %}
        <div class="movie-container">
            <img class="poster" src="{{movie.poster}}" alt="{{movie.name}}"/>
            <div class="movie-spec">
                <h3>{{movie.name}}</h3>
                <h3>⭐ {{movie.rating}}</h3>
            </div>
            <p>{{movie.summary}}</p>
            <div class="movie-actions">
            <a href="/movies/{{movie.id}}">View More</a>
            <form
            action="{{url_for('movies_list.delete_movie_by_id')}}"
            method="POST">
            <input name="movie_id" type="text" value="{{movie.id}}" hidden />
            <button class="btn btn-danger" type="submit">Delete</button>
            </form>
            <a href="/update_movie">Update</a>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}

{% block body %}
    <h1>Profile page</h1>
    <h2>Hobbies</h2>
    <ul>
        {% for hobby in hobbies %}
        <li>{{hobby}}</li>
        {% endfor %}
    </ul>
    {% endblock %}

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Register:</h1>

    <form method="POST" action="">


        <!-- action="" submit to current url -->
        <!-- Validations -->
        {{form.hidden_tag()}}

        {% if form.username.errors %}
            {% for error in form.username.errors %}
                <div style="color:red">{{error}}</div>
            {% endfor %}
        {% endif %}

        {{form.username.label}}:
        {{form.username(placeholder="Username")}}
        {{form.password.label}}
        {{form.password()}}
        {{form.submit()}}
    </form>
</body>
</html>

templates/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
</head>
<body>
<div class="sign-up-container">
    <h3>Sign Up</h3>
    <form class="sign-up-form" 
    action="{{url_for('users.sign_up_page')}}"
    method="POST">
    <h4>Username</h4>
    <input name="username" type="text" />
    <h4>Password</h4>
    <input name="password" type="password" />
    <button type="submit">Sign up</button>
    </form>
</div>
</body>
</html>

templates/update_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h4>Update Movie</h4>
    <form action="{{ url_for('movies_list.update_movie_by_id_form', id=id) }}" method="post" class="movie-form">
        <input type="text" name="name" placeholder="Name">
        <input type="text" name="poster" placeholder="Poster URL">
        <input type="number" step="0.1" name="rating" placeholder="Rating">
        <textarea name="summary" placeholder="Summary"></textarea>
        <input type="text" name="trailer" placeholder="Trailer URL">
        <button type="submit">Update Movie</button>
    </form>
</body>
</html>

templates/user_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if user %}
    <div class="user-container">
        <img class="user-pic" src="{{ user.pic }}" alt="Profile picture" />
        <p class="user-msg">
            Hello,
            <span class="user-name">
                {{ user.name }} {% if user.pro %}🚀{% else %}🎊🎊{% endif %}
            </span>
        </p>
    </div>
    {% else %}
    <p>User not found</p>
</body>
</html>